# Generated by Django 4.1.7 on 2023-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictuers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_picture', models.ImageField(upload_to='')),
                ('about_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
