# Generated by Django 4.1.7 on 2023-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictuers',
            options={'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterField(
            model_name='pictuers',
            name='about_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pictuers',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
