# Generated by Django 4.1.7 on 2023-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudaweb', '0002_alter_pictuers_options_alter_pictuers_about_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictuers',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
