# Generated by Django 4.1.7 on 2023-03-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudaweb', '0003_pictuers_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=100)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='pictuers',
            options={'verbose_name_plural': 'Pictures'},
        ),
    ]
